version: "3.4"

services:
  ponycheckup:
    image: ponycheckup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8150:8150
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
